name: Firebase App Distribution

on:
  push:
    branches:
      - main
      - develop

jobs:
  build_and_deploy:
    name: Build & Distribute APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Decode Environment Variables
        run: |
          echo "${{ secrets.ENV_PRODUCTION_BASE64 }}" | base64 --decode > .env.production

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Decode Firebase Credentials
        run: |
          echo "${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}" | base64 --decode > firebase-credentials.json

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Code Generation
        run: make gen

      - name: Build Release APK
        env:
          KEYSTORE_PATH: upload-keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: flutter build apk --release

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFile: firebase-credentials.json
          groups: qa-team
          file: build/app/outputs/flutter-apk/app-release.apk
